# 表示这是 compose 配置文件的版本
version: "2.1"
# 每个服务都是一个 Docker 容器
# 所以必须用 image 指定服务的镜像名或者从 Dockerfile 中 build 镜像
services:
    webdemo:
        # build 指定了 Dockerfile 所在的路径。docker build -t pyimage .
        build: .
        # ports 指定暴露的端口，9000 是宿主机，5000 是容器
        # 可以指定多个暴露端口
        ports:
            - "3000:3000"
        volumes:
            - .:/code
        # depends_on 设定了依赖，这里 redisdemo 会先于 pyweb 启动
        # 但是如果 redisdemo 启动时间长于 pyweb
        # 那么 pyweb 运行的时候 redisdemo 未必可用
        # depends_on:
        #     - redisdemo
